name: Build and Deploy
on:
  workflow_dispatch:
  push:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.GH_TOKEN_SECRET }}
        TARGET_REPO: reduxframework/docs
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: yarn install && yarn docs:build
        BUILD_DIR: docs/.vuepress/dist/
